# -*- coding: utf-8 -*-
"""202384041_금다은_기말과제(파이썬).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ivLub3VUk_xD-d38e2F6QNfduOrMUm4e

# 생활 습관 기록 프로그램

운동, 학습, 건강, 자기계발, 식습관의 5가지 항목에 대해

하루 동안의 생활습관을 입력하면,

해당 내용은 날짜와 함께 CSV 파일('daily_habits.csv')로 저장되는 프로그램입니다.

수업 시간에 배운 튜플, 딕셔너리, 반복문, 조건문을 활용했습니다.

# 사용 방법

1. 프로그램을 실행하면 5가지 항목에 대한 입력을 차례대로 받습니다.
2. 입력이 끝나면 오늘 날짜와 함께 ('daily_habits.csv') 파일에 저장됩니다.
3. 다음 날 실행하면 새로운 행이 자동 추가되어 일별로 기록됩니다.
"""

import csv
from datetime import datetime

# 5가지 습관 항목을 튜플로 정의합니다.
daily_habit_items = ("운동", "학습", "건강", "자기계발", "식습관")

# 오늘 날짜를 문자열 형식으로 저장합니다.
today = datetime.now().strftime("%y-%m-%d")

# 기록을 저장할 딕셔너리를 날자 포함해 생성합니다.
daily_record = {"날짜" : today}

# 사용자로부터 항목별 입력을 받습니다.
print("오늘의 생활 습관을 입력하세요.")
for item in daily_habit_items:
  answer = input(f"{item} 내용:")
  daily_record[item] = answer

# 저장할 파일명을 지정합니다.
file_name = "daily_habits.csv"

# 파일 존재 여부 확인합니다.
file_exists = False
try:
  with open(file_name, "r"):
    file_exists = True
except FileNotFoundError:
    pass

# CSV 파일에 (처음 실행 시) 헤더 포함해 기록 저장합니다.
with open(file_name, "a", newline="") as f:
  writer = csv.DictWriter(f, fieldnames = ["날짜"] + list(daily_habit_items))
  if not file_exists:
    writer.writeheader()
    writer.writerow(daily_record)

# 저장 완료 메시지 출력합니다.
print(f"{today} 기록이 저장되었습니다. ")